version: '3.7'

services:
  movies:
    build: ./app
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 192.168.50.72:8080:8080
      
    env_file:
      - ./app/.env.dev
    depends_on:
          - movies-db


  movies-db:
      image: postgres:12-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=movies
        - POSTGRES_PASSWORD=movies
        - POSTGRES_DB=movies_dev

volumes:
  postgres_data: