version: '3.7'

services:
  movies:
    build: ./app
    command: python manage.py runserver 192.168.50.72:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
